### PR TITLE
fix: performance issues

### LINKED ISSUE #4: Performance issues with the publisher
Users with limited resources complain about the plugin to use too much memory. We might want the plugin to render smarter to avoid this.

**Requirements:**
- do render GOOSE, Report, SMV and DataSet not at the same time, but only the one you need to see
- make sure that the main filter inputs are not reset when switching between the sections (sub filters can be reset)

### PR DESCRIPTION
**Pull request by noraeb**
* Refactored editor rendering to display only the active editor component
* Persistent filter value is saved when switching editors and restored in the search field when you return

closes #4

### CODE REVIEW

File: editors/gsecontrol/gse-control-editor.ts [hunk 1]
```diff
@@ -69,6 +71,13 @@ export class GseControlEditor extends BaseElementEditor {
     }
   } */
 
+  updated(changedProps: Map<string | number | symbol, unknown>) {
+    super.updated?.(changedProps);
+    if (changedProps.has('searchValue') && this.selectionList) {
+      this.selectionList.searchValue = this.searchValue;
+    }
+  }
+
```
Comment (clepski) [inline editors/gsecontrol/gse-control-editor.ts]: Do all editors have the same property and update code? If so we can move it into the baseclass `BaseElementEditor`

File: oscd-publisher.ts [hunk 2]
```diff
@@ -31,8 +41,72 @@ export default class PublisherPlugin extends ScopedElementsMixin(LitElement) {
...
+          .searchValue=${this.filterValues.SampledValue}
+          @search-change=${this.handleSearchChange('SampledValue')}
+        ></sampled-value-control-editor>`;
+      case 'DataSet':
+        return html`<data-set-editor
+          .doc=${this.doc}
+          .editCount=${this.editCount}
+          .searchValue=${this.filterValues.DataSet}
+          @search-change=${this.handleSearchChange('DataSet')}
+        ></data-set-editor>`;
```
Comment (clepski) [inline oscd-publisher.ts]: Are the `@search-change` still relevant? It seems like the value is stored when the tab changes and I dont see any `search-change` events being fired

**Review by clepski — CHANGES_REQUESTED** [review]

File: editors/gsecontrol/gse-control-editor.ts (hunk 1 above)
Comment (noraeb) [reply editors/gsecontrol/gse-control-editor.ts]: Good idea, fixed that

File: oscd-publisher.ts (hunk 2 above)
Comment (noraeb) [reply oscd-publisher.ts]: No you are right, I forgot to remove them, just fixed it

**Review by clepski — APPROVED** [review]
